---

- hosts: all
  become: true
  tasks:


  - name: install apache and php packages
    package:
      name: 
        - "{{ apache2_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"]
